config/routes.rb
Freshlly::Application.routes.draw do

  resources :users

  

  root :to => 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :postcode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @restaurants }
    end
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/new
  # GET /restaurants/new.json
  def new
    @restaurant = Restaurant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/1/edit
  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(params[:restaurant])

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render json: @restaurant, status: :created, location: @restaurant }
      else
        format.html { render action: "new" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /restaurants/1
  # PUT /restaurants/1.json
  def update
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      if @restaurant.update_attributes(params[:restaurant])
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
      <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->

  <head>

    <title>Crave - Great Healthy Food</title>

              <meta charset="utf-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
              <link href="https://fonts.googleapis.com/css?family=Limelight|Flamenco|Federo|Yesteryear|Josefin Sans|Spinnaker|Sansita One|Handlee|Droid Sans|Oswald:400,300,700" media="screen" rel="stylesheet" type="text/css" />
              <link href="stylesheets/bootstrap.css" media="screen" rel="stylesheet" type="text/css" />
              <link href="stylesheets/bootstrap-responsive.css" media="screen" rel="stylesheet" type="text/css" />
              <link href="stylesheets/common.css" media="screen" rel="stylesheet" type="text/css" />
              <link href="stylesheets/fontawesome.css" media="screen" rel="stylesheet" type="text/css" />
              <link href="stylesheets/project.css" media="screen" rel="stylesheet" type="text/css" />
              <link href="stylesheets/demo.css" media="screen" rel="stylesheet" type="text/css" />
              <!-- Typekit fonts require an account and a kit containing the fonts used. see https://typekit.com/plans for details. <script type="text/javascript" src="//use.typekit.net/YOUR_KIT_ID.js"></script>
            <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
          -->
            
            <%= stylesheet_link_tag    "application", :media => "all" %>
            <%= javascript_include_tag "application" %>
            <%= csrf_meta_tags %>
            <meta name="viewport"content="width=device-width, initial-scale=1.0">

    </head>

    <body>
	     <%= yield %>
    </body>

</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

<div id="page-wrapper">
      <div id="absolute-wrapper">    

        <div class="image image-2">
          <div class="image"><%= image_tag "big-food2.jpg" %></div>

          <div class="rectangle rectangle-1">
            <div class="dom-body-text paragraph paragraph-1">
              <p>Healthy Meals From Local Restaurants, On Demand!</p>
            </div>
            <div class="dom-body-text paragraph paragraph-2 paragraph-4">
              <p>Sign Up now to be the first to try Crave!</p>
            </div>
            <a id="Sign Up NOW"><%= f.submit "Sign Up", :class => 'btn' %></a>
            
            <%= f.text_field :postcode, :placeholder => "postcode", :class => 'textinput textinput-1' %>
            <%= f.text_field :email, :placeholder => "email", :class => 'textinput textinput-2' %>

            <% end %>

          
          </div>
        </div>
        <div class="rectangle rectangle-1 rectangle-2 rectangle-3 rectangle-4 rectangle-7">
          <div class="image image-1">
              <%= image_tag "crave-mini.png" %>
            </div>
          
          <div class="paragraph paragraph-3 paragraph-15">
            
          </div>
          
          <div class="dom-body-text paragraph paragraph-5 paragraph-6">
            <p>Great food delivered.</p>
          </div>
          <div class="rectangle rectangle-2 rectangle-3 rectangle-4 rectangle-5"></div>
        </div>
        <h2 class="heading heading-1 heading-3">Too busy to cook?&nbsp;</h2>
        <div class="dom-body-text paragraph paragraph-7 paragraph-10">
          <p>You're busy and enjoy good food.&nbsp;Long days at work mean less time for cooking. Why bother? Prioritise your life without compromising on health.</p>
        </div>
        <div class="rectangle rectangle-2 rectangle-5 rectangle-8">
          <h2 class="heading heading-1">Find the perfect meal</h2>
          <div class="dom-body-text paragraph paragraph-7">
            <p>It doesn't matter whether you're a herbivore, an omnivore or carnivore...we've got you covered! Simply find the meals that match your needs.</p>
          </div>
        </div>

        <div class="image image-3">
            <%= image_tag "empty-iphone.png" %>
        </div>
        
        <div class="rectangle rectangle-1 rectangle-6">
          <div class="image">
            <%= image_tag "diet-small.png" %>
          </div>
        </div>

        <div class="rectangle rectangle-4 rectangle-6">
          <h2 class="heading heading-1">Eat healthy, at ease!</h2>
            <div class="image">
                <%= image_tag "steelhead.jpg" %>
            </div>

          <div class="dom-body-text paragraph paragraph-7 paragraph-11">
            <p>Easy doesn't have to be junk food. At Crave we curate the healthiest and tastiest meals from local restaurants. Order-in, put your feet up and prepare to be delighted! We're launching soon.</p>
          </div>
          <div class="dom-body-text paragraph paragraph-4 paragraph-7">
            <p>Sign Up now to be the first to try Crave!</p>
          </div>

        </div>
        
<h2 class="heading heading-1 heading-4"><br /><br />Quick, healthy meals in minutes</h2>

        <h2 class="heading heading-2 heading-5">Same day ordering</h2>
        <div class="dom-body-text paragraph paragraph-7 paragraph-8 paragraph-9 paragraph-12">
          <p>Enjoy delectable meals for a healthy lifestyle without all the fuss and hard work.</p>
        </div>
        <h2 class="heading heading-2 heading-6">Cravelicious</h2>
        <div class="dom-body-text paragraph paragraph-7 paragraph-8 paragraph-9 paragraph-13">
          <p>Your food is delivered when&nbsp; and where you want it, whether it's at home or at work!</p>
        </div>
        <h2 class="heading heading-2 heading-7">Convenient Delivery</h2>
        <div class="dom-body-text paragraph paragraph-5 paragraph-7 paragraph-8 paragraph-9">
          <p>Order from a selection of fresh meals prepared by the best restaurants daily.</p>
        </div>
        <div class="rectangle rectangle-1 rectangle-2 rectangle-3 rectangle-4 rectangle-9">
          <h2 class="heading heading-1">Eager to try Crave right away?</h2>
          <div class="dom-body-text paragraph paragraph-7 paragraph-8">
            <p>We are currently testing our service with a select group of customers in Edinburgh. If you would like to be a part of this group and help us in testing out our&nbsp;service before launch, please send us an email.</p>
            <p>
              info@eatcrave.co.uk
            </p>

          </div>
          
        </div>          

          
        </div>
        <div class="image image-1 image-4">
            <div class="image-4">
            <%= image_tag "crave-mini.png" %>
          </div>
        </div>

        
                    
          
        

        <div class="dom-body-text paragraph paragraph-5 paragraph-6 paragraph-7">
          <p>Great food delivered.</p>
        </div>
        
    </div>
  </div>
    

app/views/users/invisibleedit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/invisibleindex.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:postcode) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.postcode %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>

<%= render :partial => 'form' %>

app/views/users/show.html.erb
<h2>Thank You for Signing up</h2>

<p>
  We will notify you when we launch.
</p>